### PR TITLE
Fix broken link to logging page, inconsistent post-setup instructions, ordered list numbering

### LINKED ISSUE #14: Broken link to logging page in IntelliJ setup page
The hyperlink to the `logging` setup page under the IntelliJ setup page (step 13) resolves to a 404 error. This is caused by a missing `.md` extension in the said hyperlink definition under `docs/setup/intellij.md`.

Capture

### PR DESCRIPTION
**Pull request by CheesyGamer77**
This PR fixes the following:
1) Broken hyperlink to logging setup page under IntelliJ setup page (Closes #14)
2) Inconsistent post-setup instructions. There were several different ways that the setup pages were advising users on what to do next. This PR unifies these instructions by using the post-setup instructions under the IntelliJ setup page.
3) Ordered list numbering under eclipse setup page.

### CODE REVIEW

**Comment by oliver276** [comment]
I think we should prefer to use numbering that mkdocs will transform into the 'real' numbers, like:
```md
1. First item
1. Second item
1. Third item
```
as it makes re-ordering or editing the lists a lot easier, and these will still be rendered into a normal ordered list with correct numbering

**Review by Aikovdp — COMMENTED** [review]
I'm okay with these edits, we just still need to decide on how we number those ordered lists. I've started a thread to discuss that in the #wiki-dev channel: https://discord.com/channels/125227483518861312/957280373786685530

**Comment by CheesyGamer77** [comment]
Above commit was me syncing this PR to latest commit. Not sure if anything else needs to be done in the meantime

**Comment by MinnDevelopment** [comment]
Why does this PR cover 3 different things? Please avoid scope creep like that.

**Comment by CheesyGamer77** [comment]
> Why does this PR cover 3 different things? Please avoid scope creep like that.

Sorry about that. This was my first PR in a public repo after learning git so I'm still relatively new to the github workflow. I'll be sure to keep this in mind for the future

**Review by Aikovdp — APPROVED** [review]

**Review by oliver276 — APPROVED** [review]

**Pull request merged**
